In [1]:
from quantecon.markov import DiscreteDP

In [2]:
R = [[5, 10], [-1, -float('inf')]]

In [3]:
Q = [[(0.5, 0.5), (0, 1)], [(0, 1), (0.5, 0.5)]]

In [4]:
beta = 0.95

In [5]:
ddp = DiscreteDP(R, Q, beta)

In [8]:
>>> s_indices = [0, 0, 1]  # State indices
>>> a_indices = [0, 1, 0]  # Action indices
>>> R = [5, 10, -1]
>>> Q = [(0.5, 0.5), (0, 1), (0, 1)]
>>> beta = 0.95
>>> ddp = DiscreteDP(R, Q, beta, s_indices, a_indices)

In [9]:
>>> res = ddp.solve(method='policy_iteration', v_init=[0, 0])
>>> res.sigma  # Optimal policy function

array([0, 0])

In [10]:
>>> res.v  # Optimal value function

array([ -8.57142857, -20.        ])

In [11]:
>>> res.num_iter  # Number of iterations

2

In [12]:
>>> res = ddp.solve(method='value_iteration', v_init=[0, 0],
...                 epsilon=0.01)
>>> res.sigma  # (Approximate) optimal policy function

array([0, 0])

In [13]:
>>> res.v  # (Approximate) optimal value function

array([ -8.5665053 , -19.99507673])

In [14]:
>>> res.num_iter  # Number of iterations

162

In [15]:
>>> res = ddp.solve(method='modified_policy_iteration',
...                 v_init=[0, 0], epsilon=0.01)

In [16]:
>>> res.sigma  # (Approximate) optimal policy function

array([0, 0])

In [17]:
>>> res.v  # (Approximate) optimal value function

array([ -8.57142826, -19.99999965])

In [18]:
>>> res.num_iter  # Number of iterations

3